"""batch 3: payment, shipment, promotion, product_review, return

Revision ID: 071fb5dbaeed
Revises: d4ecdb599d09
Create Date: 2026-08-03 19:41:36.075552
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "071fb5dbaeed"
down_revision: str | None = "d4ecdb599d09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promotions",
        sa.Column("promotion_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("promotion_code", sa.String(length=30), nullable=False),
        sa.Column("promotion_name", sa.String(length=150), nullable=False),
        sa.Column(
            "discount_type",
            sa.Enum(
                "percentage",
                "fixed_amount",
                name="discount_type_valid_values",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("discount_value", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.CheckConstraint(
            "discount_value >= 0", name=op.f("ck_promotions_discount_value_non_negative")
        ),
        sa.CheckConstraint(
            "ends_at > starts_at", name=op.f("ck_promotions_ends_at_after_starts_at")
        ),
        sa.PrimaryKeyConstraint("promotion_id", name=op.f("pk_promotions")),
        sa.UniqueConstraint("promotion_code", name=op.f("uq_promotions_promotion_code")),
    )
    op.create_index("ix_promotions_is_active", "promotions", ["is_active"], unique=False)
    op.create_index(
        "ix_promotions_starts_at_ends_at", "promotions", ["starts_at", "ends_at"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("payment_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum(
                "credit_card",
                "debit_card",
                "paypal",
                "gift_card",
                "bank_transfer",
                name="payment_method_valid_values",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            sa.Enum(
                "pending",
                "authorized",
                "captured",
                "failed",
                "refunded",
                "partially_refunded",
                name="payment_status_valid_values",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("transaction_reference", sa.String(length=100), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_payments_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.order_id"],
            name=op.f("fk_payments_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("payment_id", name=op.f("pk_payments")),
        sa.UniqueConstraint(
            "transaction_reference", name=op.f("uq_payments_transaction_reference")
        ),
    )
    op.create_index("ix_payments_order_id", "payments", ["order_id"], unique=False)
    op.create_index("ix_payments_paid_at", "payments", ["paid_at"], unique=False)
    op.create_index("ix_payments_payment_status", "payments", ["payment_status"], unique=False)
    op.create_table(
        "shipments",
        sa.Column("shipment_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=False),
        sa.Column("carrier", sa.String(length=50), nullable=True),
        sa.Column("tracking_number", sa.String(length=100), nullable=True),
        sa.Column(
            "shipment_status",
            sa.Enum(
                "pending",
                "in_transit",
                "delivered",
                "failed",
                "returned_to_sender",
                name="shipment_status_valid_values",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.order_id"],
            name=op.f("fk_shipments_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.warehouse_id"],
            name=op.f("fk_shipments_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("shipment_id", name=op.f("pk_shipments")),
        sa.UniqueConstraint("tracking_number", name=op.f("uq_shipments_tracking_number")),
    )
    op.create_index("ix_shipments_order_id", "shipments", ["order_id"], unique=False)
    op.create_index("ix_shipments_shipment_status", "shipments", ["shipment_status"], unique=False)
    op.create_index("ix_shipments_shipped_at", "shipments", ["shipped_at"], unique=False)
    op.create_index("ix_shipments_warehouse_id", "shipments", ["warehouse_id"], unique=False)
    op.create_table(
        "product_reviews",
        sa.Column("review_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("order_item_id", sa.BigInteger(), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("review_title", sa.String(length=200), nullable=True),
        sa.Column("review_text", sa.Text(), nullable=True),
        sa.Column("is_verified_purchase", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "review_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating BETWEEN 1 AND 5", name=op.f("ck_product_reviews_rating_in_range")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
            name=op.f("fk_product_reviews_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.order_item_id"],
            name=op.f("fk_product_reviews_order_item_id_order_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
            name=op.f("fk_product_reviews_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("review_id", name=op.f("pk_product_reviews")),
        sa.UniqueConstraint("order_item_id", name=op.f("uq_product_reviews_order_item_id")),
    )
    op.create_index(
        "ix_product_reviews_customer_id", "product_reviews", ["customer_id"], unique=False
    )
    op.create_index(
        "ix_product_reviews_product_id", "product_reviews", ["product_id"], unique=False
    )
    op.create_index(
        "ix_product_reviews_product_id_rating",
        "product_reviews",
        ["product_id", "rating"],
        unique=False,
    )
    op.create_index("ix_product_reviews_rating", "product_reviews", ["rating"], unique=False)
    op.create_index(
        "ix_product_reviews_review_date", "product_reviews", ["review_date"], unique=False
    )
    op.create_table(
        "returns",
        sa.Column("return_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("order_item_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "return_reason",
            sa.Enum(
                "defective",
                "wrong_item",
                "no_longer_needed",
                "damaged_in_shipping",
                "not_as_described",
                "other",
                name="return_reason_valid_values",
                native_enum=False,
                create_constraint=True,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "return_status",
            sa.Enum(
                "requested",
                "approved",
                "rejected",
                "refunded",
                "completed",
                name="return_status_valid_values",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="requested",
            nullable=False,
        ),
        sa.Column("quantity_returned", sa.Integer(), nullable=False),
        sa.Column("refund_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "quantity_returned > 0", name=op.f("ck_returns_quantity_returned_positive")
        ),
        sa.CheckConstraint(
            "refund_amount >= 0", name=op.f("ck_returns_refund_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.order_item_id"],
            name=op.f("fk_returns_order_item_id_order_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("return_id", name=op.f("pk_returns")),
    )
    op.create_index("ix_returns_order_item_id", "returns", ["order_item_id"], unique=False)
    op.create_index("ix_returns_requested_at", "returns", ["requested_at"], unique=False)
    op.create_index("ix_returns_return_status", "returns", ["return_status"], unique=False)
    op.create_foreign_key(
        op.f("fk_orders_promotion_id_promotions"),
        "orders",
        "promotions",
        ["promotion_id"],
        ["promotion_id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_orders_promotion_id_promotions"), "orders", type_="foreignkey")
    op.drop_index("ix_returns_return_status", table_name="returns")
    op.drop_index("ix_returns_requested_at", table_name="returns")
    op.drop_index("ix_returns_order_item_id", table_name="returns")
    op.drop_table("returns")
    op.drop_index("ix_product_reviews_review_date", table_name="product_reviews")
    op.drop_index("ix_product_reviews_rating", table_name="product_reviews")
    op.drop_index("ix_product_reviews_product_id_rating", table_name="product_reviews")
    op.drop_index("ix_product_reviews_product_id", table_name="product_reviews")
    op.drop_index("ix_product_reviews_customer_id", table_name="product_reviews")
    op.drop_table("product_reviews")
    op.drop_index("ix_shipments_warehouse_id", table_name="shipments")
    op.drop_index("ix_shipments_shipped_at", table_name="shipments")
    op.drop_index("ix_shipments_shipment_status", table_name="shipments")
    op.drop_index("ix_shipments_order_id", table_name="shipments")
    op.drop_table("shipments")
    op.drop_index("ix_payments_payment_status", table_name="payments")
    op.drop_index("ix_payments_paid_at", table_name="payments")
    op.drop_index("ix_payments_order_id", table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_promotions_starts_at_ends_at", table_name="promotions")
    op.drop_index("ix_promotions_is_active", table_name="promotions")
    op.drop_table("promotions")
    # ### end Alembic commands ###
