"""batch 1: customer, customer_address, supplier, product_category, product

Revision ID: 1df78230c534
Revises:
Create Date: 2026-08-03 19:17:13.909851
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1df78230c534"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("customer_number", sa.String(length=20), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column(
            "customer_segment",
            sa.Enum(
                "standard",
                "vip",
                "wholesale",
                name="customer_segment_valid_values",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            server_default="standard",
            nullable=False,
        ),
        sa.Column("signup_date", sa.Date(), nullable=False),
        sa.Column("signup_channel", sa.String(length=30), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("customer_id", name=op.f("pk_customers")),
        sa.UniqueConstraint("customer_number", name=op.f("uq_customers_customer_number")),
        sa.UniqueConstraint("email", name=op.f("uq_customers_email")),
    )
    op.create_index(
        "ix_customers_customer_segment", "customers", ["customer_segment"], unique=False
    )
    op.create_index("ix_customers_is_active", "customers", ["is_active"], unique=False)
    op.create_index("ix_customers_signup_date", "customers", ["signup_date"], unique=False)
    op.create_table(
        "product_categories",
        sa.Column("category_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("parent_category_id", sa.BigInteger(), nullable=True),
        sa.Column("category_name", sa.String(length=100), nullable=False),
        sa.Column("category_path", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_category_id"],
            ["product_categories.category_id"],
            name=op.f("fk_product_categories_parent_category_id_product_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("category_id", name=op.f("pk_product_categories")),
        sa.UniqueConstraint(
            "parent_category_id",
            "category_name",
            name="uq_product_categories_parent_category_id_category_name",
        ),
    )
    op.create_index(
        "ix_product_categories_category_name", "product_categories", ["category_name"], unique=False
    )
    op.create_index(
        "ix_product_categories_parent_category_id",
        "product_categories",
        ["parent_category_id"],
        unique=False,
    )
    op.create_table(
        "suppliers",
        sa.Column("supplier_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("supplier_code", sa.String(length=20), nullable=False),
        sa.Column("supplier_name", sa.String(length=200), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=30), nullable=True),
        sa.Column("country_code", sa.CHAR(length=2), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.CheckConstraint(
            "lead_time_days >= 0", name=op.f("ck_suppliers_lead_time_days_non_negative")
        ),
        sa.CheckConstraint("rating BETWEEN 0 AND 5", name=op.f("ck_suppliers_rating_in_range")),
        sa.PrimaryKeyConstraint("supplier_id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint("supplier_code", name=op.f("uq_suppliers_supplier_code")),
    )
    op.create_index("ix_suppliers_country_code", "suppliers", ["country_code"], unique=False)
    op.create_index("ix_suppliers_is_active", "suppliers", ["is_active"], unique=False)
    op.create_index("ix_suppliers_supplier_name", "suppliers", ["supplier_name"], unique=False)
    op.create_table(
        "customer_addresses",
        sa.Column("address_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "address_type",
            sa.Enum(
                "billing",
                "shipping",
                name="address_type_valid_values",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("line1", sa.String(length=255), nullable=False),
        sa.Column("line2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state_province", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country_code", sa.CHAR(length=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
            name=op.f("fk_customer_addresses_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("address_id", name=op.f("pk_customer_addresses")),
    )
    op.create_index(
        "ix_customer_addresses_country_code", "customer_addresses", ["country_code"], unique=False
    )
    op.create_index(
        "ix_customer_addresses_customer_id", "customer_addresses", ["customer_id"], unique=False
    )
    op.create_index(
        "ix_customer_addresses_one_default_per_type",
        "customer_addresses",
        ["customer_id", "address_type"],
        unique=True,
        postgresql_where=sa.text("is_default = true"),
    )
    op.create_table(
        "products",
        sa.Column("product_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("product_name", sa.String(length=255), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_id", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cost_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("launch_date", sa.Date(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.CheckConstraint("cost_price >= 0", name=op.f("ck_products_cost_price_non_negative")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_products_unit_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_categories.category_id"],
            name=op.f("fk_products_category_id_product_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.supplier_id"],
            name=op.f("fk_products_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("product_id", name=op.f("pk_products")),
        sa.UniqueConstraint("sku", name=op.f("uq_products_sku")),
    )
    op.create_index("ix_products_category_id", "products", ["category_id"], unique=False)
    op.create_index("ix_products_is_active", "products", ["is_active"], unique=False)
    op.create_index("ix_products_launch_date", "products", ["launch_date"], unique=False)
    op.create_index("ix_products_product_name", "products", ["product_name"], unique=False)
    op.create_index("ix_products_supplier_id", "products", ["supplier_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_products_supplier_id", table_name="products")
    op.drop_index("ix_products_product_name", table_name="products")
    op.drop_index("ix_products_launch_date", table_name="products")
    op.drop_index("ix_products_is_active", table_name="products")
    op.drop_index("ix_products_category_id", table_name="products")
    op.drop_table("products")
    op.drop_index(
        "ix_customer_addresses_one_default_per_type",
        table_name="customer_addresses",
        postgresql_where=sa.text("is_default = true"),
    )
    op.drop_index("ix_customer_addresses_customer_id", table_name="customer_addresses")
    op.drop_index("ix_customer_addresses_country_code", table_name="customer_addresses")
    op.drop_table("customer_addresses")
    op.drop_index("ix_suppliers_supplier_name", table_name="suppliers")
    op.drop_index("ix_suppliers_is_active", table_name="suppliers")
    op.drop_index("ix_suppliers_country_code", table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index("ix_product_categories_parent_category_id", table_name="product_categories")
    op.drop_index("ix_product_categories_category_name", table_name="product_categories")
    op.drop_table("product_categories")
    op.drop_index("ix_customers_signup_date", table_name="customers")
    op.drop_index("ix_customers_is_active", table_name="customers")
    op.drop_index("ix_customers_customer_segment", table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
