"""batch 2: warehouse, inventory, order, order_item

Revision ID: d4ecdb599d09
Revises: 1df78230c534
Create Date: 2026-08-03 19:28:20.663482
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4ecdb599d09"
down_revision: str | None = "1df78230c534"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "warehouses",
        sa.Column("warehouse_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("warehouse_code", sa.String(length=20), nullable=False),
        sa.Column("warehouse_name", sa.String(length=150), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state_province", sa.String(length=100), nullable=True),
        sa.Column("country_code", sa.CHAR(length=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("warehouse_id", name=op.f("pk_warehouses")),
        sa.UniqueConstraint("warehouse_code", name=op.f("uq_warehouses_warehouse_code")),
    )
    op.create_index("ix_warehouses_country_code", "warehouses", ["country_code"], unique=False)
    op.create_table(
        "orders",
        sa.Column("order_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("order_number", sa.String(length=20), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("promotion_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "order_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "order_status",
            sa.Enum(
                "pending",
                "confirmed",
                "shipped",
                "delivered",
                "cancelled",
                "returned",
                name="order_status_valid_values",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "sales_channel",
            sa.Enum(
                "web",
                "mobile_app",
                "marketplace",
                "phone",
                name="sales_channel_valid_values",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="web",
            nullable=False,
        ),
        sa.Column("shipping_address_line1", sa.String(length=255), nullable=False),
        sa.Column("shipping_city", sa.String(length=100), nullable=False),
        sa.Column("shipping_state_province", sa.String(length=100), nullable=True),
        sa.Column("shipping_postal_code", sa.String(length=20), nullable=True),
        sa.Column("shipping_country_code", sa.CHAR(length=2), nullable=False),
        sa.Column("subtotal_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "discount_amount", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "tax_amount", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "shipping_amount", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency_code", sa.CHAR(length=3), server_default="USD", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "discount_amount >= 0", name=op.f("ck_orders_discount_amount_non_negative")
        ),
        sa.CheckConstraint(
            "shipping_amount >= 0", name=op.f("ck_orders_shipping_amount_non_negative")
        ),
        sa.CheckConstraint(
            "subtotal_amount >= 0", name=op.f("ck_orders_subtotal_amount_non_negative")
        ),
        sa.CheckConstraint("tax_amount >= 0", name=op.f("ck_orders_tax_amount_non_negative")),
        sa.CheckConstraint("total_amount >= 0", name=op.f("ck_orders_total_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
            name=op.f("fk_orders_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("order_id", name=op.f("pk_orders")),
        sa.UniqueConstraint("order_number", name=op.f("uq_orders_order_number")),
    )
    op.create_index("ix_orders_customer_id", "orders", ["customer_id"], unique=False)
    op.create_index(
        "ix_orders_customer_id_order_date", "orders", ["customer_id", "order_date"], unique=False
    )
    op.create_index("ix_orders_order_date", "orders", ["order_date"], unique=False)
    op.create_index("ix_orders_order_status", "orders", ["order_status"], unique=False)
    op.create_index("ix_orders_promotion_id", "orders", ["promotion_id"], unique=False)
    op.create_index("ix_orders_sales_channel", "orders", ["sales_channel"], unique=False)
    op.create_table(
        "inventory",
        sa.Column("inventory_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity_on_hand", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reorder_level", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_restocked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity_on_hand >= 0", name=op.f("ck_inventory_quantity_on_hand_non_negative")
        ),
        sa.CheckConstraint(
            "reorder_level >= 0", name=op.f("ck_inventory_reorder_level_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
            name=op.f("fk_inventory_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.warehouse_id"],
            name=op.f("fk_inventory_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("inventory_id", name=op.f("pk_inventory")),
        sa.UniqueConstraint(
            "product_id", "warehouse_id", name="uq_inventory_product_id_warehouse_id"
        ),
    )
    op.create_index("ix_inventory_product_id", "inventory", ["product_id"], unique=False)
    op.create_index(
        "ix_inventory_quantity_on_hand", "inventory", ["quantity_on_hand"], unique=False
    )
    op.create_index("ix_inventory_warehouse_id", "inventory", ["warehouse_id"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("order_item_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "discount_amount", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
        sa.Column("line_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "discount_amount >= 0", name=op.f("ck_order_items_discount_amount_non_negative")
        ),
        sa.CheckConstraint("line_total >= 0", name=op.f("ck_order_items_line_total_non_negative")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_quantity_positive")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_order_items_unit_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.order_id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
            name=op.f("fk_order_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("order_item_id", name=op.f("pk_order_items")),
        sa.UniqueConstraint("order_id", "product_id", name="uq_order_items_order_id_product_id"),
    )
    op.create_index("ix_order_items_order_id", "order_items", ["order_id"], unique=False)
    op.create_index("ix_order_items_product_id", "order_items", ["product_id"], unique=False)
    op.create_index(
        "ix_order_items_product_id_order_id",
        "order_items",
        ["product_id", "order_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_order_items_product_id_order_id", table_name="order_items")
    op.drop_index("ix_order_items_product_id", table_name="order_items")
    op.drop_index("ix_order_items_order_id", table_name="order_items")
    op.drop_table("order_items")
    op.drop_index("ix_inventory_warehouse_id", table_name="inventory")
    op.drop_index("ix_inventory_quantity_on_hand", table_name="inventory")
    op.drop_index("ix_inventory_product_id", table_name="inventory")
    op.drop_table("inventory")
    op.drop_index("ix_orders_sales_channel", table_name="orders")
    op.drop_index("ix_orders_promotion_id", table_name="orders")
    op.drop_index("ix_orders_order_status", table_name="orders")
    op.drop_index("ix_orders_order_date", table_name="orders")
    op.drop_index("ix_orders_customer_id_order_date", table_name="orders")
    op.drop_index("ix_orders_customer_id", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_warehouses_country_code", table_name="warehouses")
    op.drop_table("warehouses")
    # ### end Alembic commands ###
