"""`POST /query/validate` -- validate externally supplied SQL. Never generates or repairs it.

`SQLValidationEngine.validate` only accepts a `GeneratedSQL`, which
normally carries real LLM provenance (`llm_metrics`, `raw_llm_content`,
...). SQL supplied directly over HTTP has none of that -- no LLM call
produced it -- so this router wraps it in a placeholder `GeneratedSQL`
envelope with zero-cost, clearly-synthetic metrics, purely so the real,
unmodified `SQLValidationEngine` can be called. This wrapping is
presentation-layer request adaptation, not SQL generation: no SQL text
is invented, altered, or normalized beyond what `SQLValidationEngine`
itself would see from a real pipeline run.

Requires at least `ANALYST` (Phase 22B) -- part of the same `/query/*` family as `POST /query`,
protected the same way even though this one doesn't call the LLM.
"""

from __future__ import annotations

from fastapi import APIRouter, status

from querymind.api.dependencies import RateLimitQuery, RequireAnalyst, SQLValidationEngineDep
from querymind.api.models.request import SqlInputRequest
from querymind.llm.models import FinishReason, GenerationMetrics, LLMProvider, TokenUsage
from querymind.query_library.models import SQLDialect
from querymind.sql_generation.models import (
    ExtractionMethod,
    GeneratedSQL,
    SQLGenerationStatistics,
)
from querymind.sql_generation.parser import StatementTypeDetector
from querymind.sql_validation.models import SQLValidationResult

router = APIRouter(prefix="/query/validate", tags=["query"])

_STATEMENT_TYPE_DETECTOR = StatementTypeDetector()


def _wrap_as_generated_sql(sql: str, dialect: SQLDialect) -> GeneratedSQL:
    """Wrap externally supplied `sql` in a placeholder `GeneratedSQL` envelope.

    `llm_metrics`/`statistics` are honest placeholders (zero latency, zero
    tokens) -- there is no real LLM call to report metrics for.
    """
    return GeneratedSQL(
        sql=sql,
        statement_type=_STATEMENT_TYPE_DETECTOR.detect(sql),
        raw_llm_content=sql,
        dialect=dialect,
        llm_metrics=GenerationMetrics(
            provider=LLMProvider.CLAUDE,
            model="external",
            latency_ms=0.0,
            token_usage=TokenUsage(prompt_tokens=0, completion_tokens=0),
            retry_count=0,
            finish_reason=FinishReason.COMPLETE,
        ),
        statistics=SQLGenerationStatistics(
            extraction_method=ExtractionMethod.RAW_TEXT,
            raw_sql_length=len(sql),
            normalized_sql_length=len(sql),
            normalization_changed_sql=False,
            generation_latency_ms=0.0,
        ),
    )


@router.post(
    "",
    response_model=SQLValidationResult,
    status_code=status.HTTP_200_OK,
    summary="Validate externally supplied SQL",
    description=(
        "Runs the same ten independent, read-only validators `/query`'s own pipeline uses "
        "against SQL text supplied directly, rather than generated by the LLM. Requires at "
        "least the `analyst` role."
    ),
    responses={
        200: {
            "description": "Validation completed -- check `is_valid`, not the HTTP status.",
            "content": {
                "application/json": {
                    "example": {"is_valid": False, "errors": [{"code": "unknown_table"}]}
                }
            },
        }
    },
)
async def validate_sql(
    request: SqlInputRequest,
    validation_engine: SQLValidationEngineDep,
    _analyst: RequireAnalyst,
    _rate_limit: RateLimitQuery,
) -> SQLValidationResult:
    generated_sql = _wrap_as_generated_sql(request.sql, request.dialect)
    return validation_engine.validate(generated_sql)
